language: python
dist: xenial
python:
  - "3.5"
addons:
  apt:
    packages:
    - enchant

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - python setup.py install
  - pip install codecov
  - pip install twine
  - pip install flake8
  - python -m nltk.downloader stopwords
  - make word2vec/arwiki-20200501-learned_vectors.50_cell.10k.kv
  - make word2vec/cswiki-20200501-learned_vectors.50_cell.10k.kv
  - make word2vec/enwiki-20200501-learned_vectors.50_cell.10k.kv
  - make word2vec/euwiki-20201201-learned_vectors.50_cell.10k.kv
  - make word2vec/huwiki-20201201-learned_vectors.50_cell.10k.kv
  - make word2vec/hywiki-20201201-learned_vectors.50_cell.10k.kv
  - make word2vec/kowiki-20200501-learned_vectors.50_cell.10k.kv
  - make word2vec/srwiki-20201201-learned_vectors.50_cell.10k.kv
  - make word2vec/ukwiki-20201201-learned_vectors.50_cell.10k.kv
  - make word2vec/viwiki-20200501-learned_vectors.50_cell.10k.kv
  - make word2vec/wikidata-20200501-learned_vectors.50_cell.10k.kv

script:
  - flake8 .
  - coverage run --source drafttopic -m pytest -m "not nottravis"
  - sphinx-build -anW -b html docs dist/docs
  - sphinx-build -b linkcheck docs dist/docs

after_success:
  - coverage report
  - codecov

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  on:
#    branch: master
